 - stage: test
      os: osx
      language: sh
      env:
        - TOXENV=py3
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      before_cache:
        # - brew cleanup
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          # - "$HOME/Library/Caches/Homebrew"
          - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          # update: true
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
      install: pip install --upgrade <your-packages>
      script: <your-script>

language: python
matrix:  
  include:
    - name: "Python: 3.5"
      os: osx
      language: generic
      python: "3.5"
      env:
        - TOXENV=py3
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
        - PYTHON_VERSION=3.5
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        - directories:
          - $HOME/Library/Caches/pip
      addons:
        homebrew:
          # update: true
          packages: pyenv
      before_install:
        - pyenv PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.5.0
        - pyenv virtualenv 3.5.0 test
        - pyenv activate test
        - pyenv rehash
        #- python3 -m pip install --upgrade virtualenv
        #- virtualenv -p python3 --system-site-packages "$HOME/venv"
        #- source "$HOME/venv/bin/activate"
install:
- bash $TRAVIS_BUILD_DIR/build.sh $TRAVIS_OS_NAME $PYTHON_VERSION
services:
- xvfb
deploy:
  provider: releases
  api_key:
    secure: ad5sOFsBOVecCOtjhX8ZGyQ7JYZqGFtcwLOzaxudpch+IFcOkCe3q0NF1CMVPWg4OwqF3vVLUp7IUwTorfPn6WbmuaqDC3LI4dCs5jsmjXzTuYzxvRaSeGookCCsQ4+AYO5f4zoOJ/Lnq2FU99z5zG9BFzCKeQ6XeCGui9HqsElSSR2FMDlqKL5DgcJW4XMEJu6zHattxEPukyijXvrVKC76SpLMLm69XkrL0OiUiHX8SiurE+K3choFau13vsHRjhKHUzKhLRWINX0uqvITHQJ0YEhiTXyp0xPwuHJz1Cf19UwkE/z1KAosI3iLdPzKIHJnz+58Oa0CMj+6iJFX2lV0sNPkqXA3ywTvhmEUmLniwOALZBi/2YuThFiKV67gebCCkitbZyDgvuKjrbtIfrAYSUrEnMAfCvWcQaX7X0j5xE4DK1Opd94mdUXtSN+1L3qprVPsruuRfB5Csxn1+FjQvFeaWH5YIAQImGvtqBPpmE8K8Q0SIWMvQ5DLVT99n3IB4Tr71uz9VaCCdxSzEouedB6c8kNsX6/Tw0JPna+w2HAFfJ1ZeOQc8EsCgiMNGAYWKSmJPJR3v+AMXRsyF+FdhfjqpaNcl3tK/RIX4xQHtu5vlpiqCjmWcx2IOG48lP61di20K3yhlWcT9h4LMzG9or5pioWH1ppITL8BYsg=
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    tags: true
    condition: $PYTHON_VERSION = 3.5
    repo: cunyap/test_osx_ci
